### ISSUE TITLE
Word integration is broken

### ISSUE THREAD

**Issue by fbennett** [Juris-M/zotero-standalone-build#2]
This issue is caused by setting `name` to `Jurism` in `application.ini`. The value needs to be set to `Zotero` for the plugin connection to work.

Unfortunately, the plugin still needs to be specially reconfigured, because it will not run in JM Standalone unless it is declared to be compatible with a range of its versions.

Worth checking once with Zotero devs, to see if the version compatibility declaration can be included in their version of the plugin. Failing that, we'll need to fork and hack it.

**Comment by fbennett** [comment]
On second thought, since the team Zotero build steps pull in the plugin code in source form, then make a copy, we can stream-edit the extended compatibility marker into the copy on the fly. No need to bother the Zotero devs, and we get to reuse their code. That's two wins. Win-win.

**Comment by rischconsulting** [comment]
New Word plugin works, though there remains an additional group under a separate "add in" menu that seems off.

However, the Abbrevs button is greyed out in the plugin.

**Comment by fbennett** [comment]
Progress. In Word, I get one button group "Zotero" and another "Add-Ins"
(but in Japanese, because of the system). Is it like that? If not, can you
send a screenshot?

On Sep 5, 2017 10:59 AM, "rischconsulting" <notifications@github.com> wrote:

New Word plugin works, though there remains an additional group under a
separate "add in" menu that seems off.

However, the Abbrevs button is greyed out in the plugin.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Juris-M/zotero-standalone-build/issues/2#issuecomment-327051928>,
or mute the thread

**Comment by rischconsulting** [comment]
Correct - I get the two groups. I also see the .dot and .dotm in Word Add-ins. I suspect both the new and older (word 2003 and before) versions of the add-ins are being installed. I also think it was like this before and I just never paid attention.

**Comment by fbennett** [comment]
I tried removing both files (zotero.dot and zotero.dotm), and then reinstalling integration support from Juris-M 5.0. Both files come back, and we again get two menus. Removing the files one at a time, it looks like the larger one (about 50k) creates the old-style buttons under "Add-ins," and the smaller one (about 35k) creates the buttons that show up under "Zotero."

We're now using the Zotero plugin code verbatim (just tweaking a compatibility parameter to allow it to install). It does seem a little odd, but this may be what we would get from vanilla Zotero as well. In any case, you can make one of the menus go away by removing the file, so I'll close this issue for now.
