### ISSUE TITLE
Abbreviations: suppression

### ISSUE THREAD

**Issue by fbennett** [Juris-M/zotero-standalone-build#4]
Check with Michael on whether we can do better with jurisdiction suppression.

**Comment by fbennett** [comment]
@rischconsulting Thanks for your mail. There were two issues around abbreviations I think.

1. The abbrevs related to legal resources, at least (which are the important ones) are pretty much in a DIY state, in that the lists shipped with the tool are not taking effect.
2. The new jurisdiction suppression logic requires explicit flagging of each jurisdiction (that is, suppression is not inherited).

Re (1), I think I can help here, but it will take some time. Playing with the tool, I see that an abbreviation is lost when I suppress/unsuppress an element of the jurisdiction. That bothers me, and I need to think about it. It would be alarming to me if I set a set of abbreviations and they suddenly disappeared because of a change in a separate setting. It seems like abbreviations of a jurisdiction should be tied to the underlying code-slug (which we have and can use), rather than the ephemeral visual representation. So I'll look into making that change. It might take awhile---even as I write here, I'm thinking of edge cases that will be a challenge.

Once the mapping elements for jurisdiction data are stable, I can go through the Indigo Book and set up bundled abbreviations for commonly cited Federal and state courts, which should help somewhat.

Re (2), the per-jurisdiction-code suppression logic is by intention. If suppression is inheritable (as I think it was before maybe?), cites would be losing arbitrary information that is probably be needed to compose a correct citation---for example, "2d Cir." is derived from the jurisdiction data.

There are some ways that handling jurisdiction markers can be made less cumbersome, but I'll leave this for the moment, and go back to the cave and think about it.

**Comment by rischconsulting** [comment]
Thanks for the followup. My thoughts:
On 1: I thought this was already happening on list import. Didn’t it used to? I don’t remember putting every single abbreviation in for the past, though maybe I did.
On 2: Maybe we are thinking of different type of suppression. Right now, the cite drops in two different pieces of information: US|Second Circuit drops in “Second Circuit” or something like that and Court of Appeals (in “Place” drops in “Court of Appeals”). So, I suppress US|Second Circuit at the top, and I set an Abbrev. To 2d. Cir. for the second, which works well.

But it seems like I should be able to suppress ALL of the jurisdictions at the top – I don’t want any of them in bluebook format. And then some of the basic court abbreviations should be automatic. At the very least, there should be detailed instructions on how to use Abbrevs to get a bluebook cite, because I’m trying to push this out to my faculty as a great blue book cite program (which it is!) but I fear that no one will figure out how to actually make it do that.

On a side note, losing all of the Abbrevs that were there is killer – I have a paper with 100+ cites and I can’t update it anymore, it would be chaos (especially because the Abbrevs button is greyed out in word integrations)

**Comment by fbennett** [comment]
Thanks - feedback at this point is pretty critical. It does seem like I'm getting tangled up my thinking a bit. We:ll get it sorted though.

I'm concerned to restore your abbreviations. When you search the OS for 'abbreviations.sqlite', and visit the director(y|ies) where each is located, do you see (a) any copies that are larger than the one you have in the data directory, or (b) any copies with an extension like bak, or a number, which are larger?

**Comment by rischconsulting** [comment]
On one machine, I’ve got 3 (2 are backups) abbrevs-filter.sqlite, all date modified  1/4/17, all the same size (about 2MB). On a second machine, I’ve got a few older ones, bigger. A quick search doesn’t find abbreviations.sqlite, though I’ll need to do a more thorough search later.

Regards,
MR

**Comment by rischconsulting** [comment]
I may not have updated to 5 on that machine. I'll have to check later

Regards,
MR (from mobile)

-----Original Message-----

**Comment by rischconsulting** [comment]
OK, last point – sorry for the multiple emails. On my other machine, there were multiple copies of abbrevs-filter.sqlite, and the older ones were bigger. I saved a copy of the older one (and the newer one), renamed the older one to one without an extension, and reloaded. No difference. Maybe I just don’t have the right file at all, and that’s why list importing is failing too?

Regards,
MR

**Comment by fbennett** [comment]
@rischconsulting Thanks for checking. I wrote last night from memory, and got the name of the database file wrong. `abbrevs-filter.sql` it is.

If the abbreviations you want to migrate are legal abbrevs, the matches are probably not turning up because the match-text received from the processor has changed. Could you send me a copy of one of the 2mb database files as an email attachment? I can use that to confirm the expected match pattern, and to do migration testing.

**Comment by fbennett** [comment]
Thanks again for your note on jurisdiction/court matches. You are exactly right. While putting together the 5.0-compatible version of the abbrevs filter, I made a bad assumption, relying on jurisdiction rather than the institution for rendered abbreviations. Misunderstood my own data structures.

When rendered, "jurisdiction" should only show a country name, for use in mixed-jurisdiction texts where that needs to be specified for clarity. But as a full code, the information it provides is useful only behind the scenes, to peg a given institution abbreviation to a particular jurisdictional scope. The code itself, and its descriptive string, never needs to be rendered directly. Don't know what I was thinking there.

The coding tweaks needed are not major, I think there is a good prospect for getting back on track within a few days.

**Comment by rischconsulting** [comment]
I attached a file to a prior email. Let me know if it is on GitHub. If not, I'll email separately later

Regards,
MR (from mobile)
________________________________

**Comment by fbennett** [comment]
Missed it, sorry. Will fetch it from my account later.

Meanwhile, I've looked at behind-the-scenes matching in 4.0 and 5.0, and it may be a simpler fix than I initially thought. In 4.0, abbrev match strings export in lowercase. In 5.0, they are case-sensitive. If the abbrevs filter does not force to lowercase internally (and I think it doesn't yet), that would explain why matches are failing. A small tweak may bring everything up for you again.

The jurisdiction-suppression issue will take some effort to set right, but that's far less worrying (from a development perspective) than the wholesale failure of matches to existing user lists.

I hope to get this fixed up within the day. I have a private trip to the US coming up (west coast), and there be paperwork and catch-up to do before departure. Feeling relieved at the moment that the most serious initial problems with the release seem to be under control.

**Comment by fbennett** [comment]
@rischconsulting Progress this morning. I've peeked inside your abbreviations data file, and indeed the match strings are all in lowercase. That's good, and I'm glad to see that the 4.0 version of the abbrevs filter has been working that way.

So what we need is for the Abbreviations Filter to match on the basis of normalized (i.e. lowercase) data. In terms of coding, it would be quite difficult to display the original mixed-case text pulled from the fields, but match on normalized data under the hood. The reasons behind that assertion are a little bit involved, but I'm pretty certain that in 4.0, which exactly did display mixed-case and match on lowercase, behavior would have sometimes surprised the user. And we don't like surprises.

It's a fairly simple thing to fix, though. The data remains the same, since it's been stored correctly. All that's needed is to similarly normalize the match-key texts, which show through in the abbrevs edit pane. I've identified the spots in the code where that needs to happen, and built an alpha client to confirm that the revised logic actually works. There are some little things to tidy up, but I should have a test release ready in a bit.

I have appointments at Uni today, and will need to make the jump soon. But I'll push forward on this during the day, and should have a beta release out soon---and I'll test it against your database, to be sure that the fix will actually improve things for you.

**Comment by rischconsulting** [comment]
Awesome, thanks!

Regards,
MR (from mobile)

-----Original Message-----

**Comment by fbennett** [comment]
@rischconsulting  I think I have a client ready that will behave correctly for abbreviations. I've built it for Linux and done some initial testing. It's late hear, and I need to get some sleep. Tomorrow I'll do beta builds for Mac and Windows, and send you a link. If it looks okay, we can push it out as the next release. Here are the changes:

1. Instead of printing the full jurisdiction, styles will be amended to print only the country name, in most cases.
2. The Suppress bubbles in the Abbrevs Filter will offer only country names.
3. Abbreviation keys (field values) will be normalized to lowercase for matching purposes.

It turned out to be quite a bit more work than I expected, with changes in the core client, the abbrevs filter, the styles served by the Myles plugin, and the citation processor. But I think we have a good result---here's looking forward to tomorrow.

**Comment by rischconsulting** [comment]
Looking forward to it!

Regards,
MR

**Comment by fbennett** [comment]
@rischconsulting It's been awhile since Juris-M has seen a feature overhaul on this scale. Had forgotten how fun it is (seriously). A programming analog to base jumping. :-)

My idea of adding a `country` variable derived from `jurisdiction` was not a good one. There might be federal subjurisdictions (California, Tasmania, Bavaria ...) that should appear in some citation forms. So I've wound most of that change out, and I'm now running trials with a new `jurisdiction-depth` attribute that will allow us to limit the rendered form of `jurisdiction` to the country name, or extended it slightly for the (no doubt limited) cases where more information should be displayed.

Re the "suppress" functionality, limiting suppression to the country element still makes sense, I think. In the rare cases that subjurisdiction information is needed, we wouldn't want to suppress it.

**Comment by rischconsulting** [comment]
What’s weird is that I thought this worked before. But maybe it didn’t – I do remember asking about it for a while on the old version. Thanks for your efforts on this.

Regards,
MR

**Comment by fbennett** [comment]
Yes, I think it was working for US law, but we had some pain here with comparative law theses that needed to show jurisdiction info. I've just finished a note on the latest changes, which I'll put up when the releases go live. The client code is ready, and the Windows and Mac builds are coming up soon. Fingers cross, but I think we may finally have a stable solution that works all around.

More soon!

**Comment by fbennett** [comment]
@rischconsulting It's [out now](https://juris-m.github.io/downloads), and a [wordy post](https://juris-m.github.io/blog/jurism/announcement/2017/09/09/abbreviations.html) on abbreviation issues is up.

**Comment by rischconsulting** [comment]
This is a big step forward, but I’m sad to report that it’s not there yet. I think your change messes with how they used to be done. This is a long windup, so I’ll repeat the punch line below here: I think you are looking to the wrong CategoryID when you are matching your abbreviations. You should be matching to CatID 3 Place and NOT CatID 5 Institution

Here is how Georgia-Pacific now renders:
Georgia-Pacific Corp. v. United States Plywood Corp., 243 F. Supp. 500 (1965).
It should be Georgia-Pacific Corp. v. United States Plywood Corp., 243 F. Supp. 500 ( S.D.N.Y. 1965).

In JM4.0, the codes were this:  Jurisdiction: US|Second Circuit, Court: S.D. New York District Court (SIDE NOTE: these fields are no longer right next to each other. Did they used to be? It’s sort of a bummer that they are not, since Google Scholar’s translator doesn’t get it right and you have to change it every time)

In JM5.0, the codes are: Jurisdiction: US|Second Circuit|S.D. New York, Court: District Court (if you try to do it the old way, it auto fixes to this – was that you?).

All well and good. But somewhere in there, the two pieces are not being read properly. I could have sworn that all my abbrevs were in the “Places” page, but that page is now blank. Also, the institution page is filled with !here>>> codes, because I was blocking that part out, because the “place” had all the info we needed. So, I looked at the sqlite file, and my memory is vindicated. Here is the listings for S.D.N.Y. in the db (and for 2d. Cir., which also doesn’t work, for good measure, because it better illustrates the point I’m about to make):

"22"       "1" default          "3" place                              "2940" us|second circuit               "2941" 2d Cir.
"22"       "2" us                    "5" institution part          "3202"   second circuit court of appeals "2941" 2d Cir.
"22"       "1" default          "3" place              "2698" us|second circuit|s.d. new york  "2699" S.D.N.Y.

I don’t know where the middle one comes from – I suspect that it’s the “old school” version – in my DB, where “institution part” cat 5 is “district court” of US|Federal Circuit (because I couldn’t suppress that for some reason), then I have the abbrev set to !here>>> (which leads me to believe that the automated consolidation of court and jurisdiction happened under the old version as well).

In any event – I don’t know what you are looking at for the abbreviation, but I think you have to look at categoryID 3 and NOT categoryID 5. It is the “Institution Part” that must be suppressed and the “Place” that must be shown – not vice versa.

Regards,
MR

**Comment by fbennett** [comment]
The 'jurisdiction' variable is in the 'place' category. The court name is
in the 'institution part' category. It has always been so. Fields are not
combined in any way.

 As I described in the post, the thing to abbreviate is the court name, as
written against a given jurisdiction. An abbreviation of jurisdiction alone
loses information -- there may be multiple bodies inside a jurisdictional
scope, each with a specific abbreviated name.

We still need to get you going though. I'll look at building a pre-bundled
list for import. Which style would have the best set of abbrevs to work
from?





On Sep 10, 2017 4:04 AM, "rischconsulting" <notifications@github.com> wrote:

This is a big step forward, but I’m sad to report that it’s not there yet.
I think your change messes with how they used to be done. This is a long
windup, so I’ll repeat the punch line below here: I think you are looking
to the wrong CategoryID when you are matching your abbreviations. You
should be matching to CatID 3 Place and NOT CatID 5 Institution

Here is how Georgia-Pacific now renders:
Georgia-Pacific Corp. v. United States Plywood Corp., 243 F. Supp. 500
(1965).
It should be Georgia-Pacific Corp. v. United States Plywood Corp., 243 F.
Supp. 500 ( S.D.N.Y. 1965).

In JM4.0, the codes were this: Jurisdiction: US|Second Circuit, Court: S.D.
New York District Court (SIDE NOTE: these fields are no longer right next
to each other. Did they used to be? It’s sort of a bummer that they are
not, since Google Scholar’s translator doesn’t get it right and you have to
change it every time)

In JM5.0, the codes are: Jurisdiction: US|Second Circuit|S.D. New York,
Court: District Court (if you try to do it the old way, it auto fixes to
this – was that you?).

All well and good. But somewhere in there, the two pieces are not being
read properly. I could have sworn that all my abbrevs were in the “Places”
page, but that page is now blank. Also, the institution page is filled with
!here>>> codes, because I was blocking that part out, because the “place”
had all the info we needed. So, I looked at the sqlite file, and my memory
is vindicated. Here is the listings for S.D.N.Y. in the db (and for 2d.
Cir., which also doesn’t work, for good measure, because it better
illustrates the point I’m about to make):

"22" "1" default "3" place "2940" us|second circuit "2941" 2d Cir.
"22" "2" us "5" institution part "3202" second circuit court of appeals
"2941" 2d Cir.
"22" "1" default "3" place "2698" us|second circuit|s.d. new york "2699"
S.D.N.Y.

I don’t know where the middle one comes from – I suspect that it’s the “old
school” version – in my DB, where “institution part” cat 5 is “district
court” of US|Federal Circuit (because I couldn’t suppress that for some
reason), then I have the abbrev set to !here>>> (which leads me to believe
that the automated consolidation of court and jurisdiction happened under
the old version as well).

In any event – I don’t know what you are looking at for the abbreviation,
but I think you have to look at categoryID 3 and NOT categoryID 5. It is
the “Institution Part” that must be suppressed and the “Place” that must be
shown – not vice versa.

Regards,
MR

**Comment by rischconsulting** [comment]
Indigo law review is best. But my concern is that everyone else who has imported lists and/or set up any court abbrevs will have this problem. The new way may be right, but it’s the exact opposite of how it was before. I can fix this by just changing all the 3’s to 5’s in my sqlite.

More broadly, in my DB, the jurisdiction has ALL of the information, at least for the US. US|Second Circuit|S.D.N.Y.  The “Court Name” says “District Court” which a) has no entry and b) is non-unique. And if I TRY to put the court name in to the Court field (which is what I used to do), it immediately changes it to District Court and updates the “jurisdiction” field to another layer of granularity.

Regards,
MR

**Comment by rischconsulting** [comment]
Screenshot:
https://www.dropbox.com/s/o6rnluazkmw9c5v/Screenshot%202017-09-09%2018.50.56.png?dl=0


Regards,
MR

**Comment by fbennett** [comment]
On Sun, Sep 10, 2017 at 7:49 AM, rischconsulting <notifications@github.com>
wrote:

> Indigo law review is best. But my concern is that everyone else who has
> imported lists and/or set up any court abbrevs will have this problem. The
> new way may be right, but it’s the exact opposite of how it was before. I
> can fix this by just changing all the 3’s to 5’s in my sqlite.
>

Don't change the category digits in the database directly. The match string
on your entries is from the jurisdiction field. Changing the category value
will force the filter to look for the same value in one of the 'place'
variables, where it doesn't exist. The entries can be converted, but it
will require some sleight of hand.

The pain will be much less if I produce a standard list of abbreviations
that covers the common cases.

More broadly, in my DB, the jurisdiction has ALL of the information, at
> least for the US. US|Second Circuit|S.D.N.Y. The “Court Name” says
> “District Court” which a) has no entry and b) is non-unique. And if I TRY
> to put the court name in to the Court field (which is what I used to do),
> it immediately changes it to District Court and updates the “jurisdiction”
> field to another layer of granularity.
>

The jurisdiction does not have all of the information. It expresses only
jurisdictional scope, not the body issuing the document cited. In each
federal district, there is a District Court and a Bankruptcy Court. Several
circuits have both a Court of Appeal and a Bankruptcy Appellate Panel.

I realize that this is annoying, but things will be much simpler if we make
this jump now.

I'll dig into the list data today, and post again when I have something to
report.

**Comment by rischconsulting** [comment]
I had already figured out not to change it. And I get that Court can have multiple entries (this is true in the Federal Circuit as well). My concern is just that EVERYONE’s files will be bad. Maybe hardly anyone uses it, so no big deal. That’s why I wonder whether a converter might be a good way to go. Then again, I see no “institution part” for district court for the southern district of new York, so it may need to be all new lists. But that’s going to be rough.

Regards,
MR

**Comment by rischconsulting** [comment]
OK, I just created my own abbreviation, and:

  1.  I see what you mean about how it works now, and I think it’s clever, and
  2.  I see why a simple translator won’t work (at least not one that I can create). There’s not even a “Bankruptcy Court” listing in strings like there is for “district court”, so there’s nothing to tie it to. I frankly wonder how it ever worked before. This will take a re-tying of all the jurisdictions and courts to the appropriate abbreviations. Maybe that’s simpler than it sounds if you have the list of all of them…

**Comment by fbennett** [comment]
I'll definitely do my best to smooth the way. The chaos over this a failure
of design and documentation on my part. Friends in the CSL group are much
better than I am at specification work, but when I described the
requirements of legal citation patterns to them, they kind of said, "good
luck with that." We're in the groove now, though, and things will start to
tighten up.

Thanks for your patience!

Frank

**Comment by fbennett** [comment]
I've opened an issue for the remapping of abbreviations. Closing this, as the other issues in the thread have been covered.
