### ISSUE TITLE
Abbrevs button greyed out in Word Integration

### ISSUE THREAD

**Issue by rischconsulting** [Juris-M/zotero-standalone-build#6]
The button is greyed and unclickable out both in the new view and the classic view.
Screenshot: https://www.dropbox.com/s/w5y5won1z9pbbem/Screenshot%202017-09-09%2019.59.32.png?dl=0

**Comment by fbennett** [comment]
It's greyed out when a document is first opened, because the processor hasn't yet been run over the citations. If you insert a citation and then open it for editing, the button should wake up.

**Comment by rischconsulting** [comment]
Ok – confirmed it’s working

Regards,
MR
