### ISSUE TITLE
is jurism.md note still accurate?

### ISSUE THREAD

**Issue by duncdrum** [Juris-M/zotero-standalone-build#8]
adding and updating submodules does not point to jurism after forking, so i think instead of specifying branch one would to need to switch sources first.

**Comment by duncdrum** [comment]
see d3adbce1e87e689509309ae5e00f61a5b8697f83

**Comment by fbennett** [comment]
The note was added back in 2015, when there was a very different build process for 4.0 (and when Juris-M build steps probably diverged quite a bit from what team Zotero was using).

In the 5.0 configuration, the core is not added to ``zotero-standalone-build`` as a submodule at all---it's copied in from ``../zotero-build/xpi/build/staging``, at [line 173](https://github.com/Juris-M/zotero-standalone-build/blob/master/build.sh#L173) of ``build.sh``. Copying the code in at build time allows use of the same build framework for code from different commits in the ``../jurism`` repo.
