### ISSUE TITLE
$ZOTERO_SOURCE_DIR points to zotero-client/install.rdf…

### ISSUE THREAD

**Issue by duncdrum** [Juris-M/zotero-standalone-build#9]
it should point to 
`jurism/install.rdf`

constequently:
```bash
./scripts/dir_build
```

fails with 
```
Can't open /Users/halalpha/Documents/gits/zotero-client/install.rdf: No such
 file or directory.
./scripts/dir_build: line 59: [: =: unary operator expected
fatal: Cannot change to '/Users/halalpha/Documents/gits/zotero-client': No s
uch file or directory
```

which leads to:
```bash
./build.sh -p m
Content at /Users/halalpha/Documents/gits/zotero-build/xpi/build/staging/ is
 not a Juris-M client.
```

**Comment by fbennett** [comment]
The instructions do need a fix there. To save typing, in the Juris-M fork I've hacked ``./build.sh`` to sniff the channel, version, and platform from the environment, and removed the options for those parameters. So after setting ``ZOTERO_BUILD_DIR`` in a config file (a step that was missing from the README), ``./scripts/dir_build -p l`` still fails for me with ``illegal option -- d``, but we can get the same result with just ``./build.sh -s``.

I'll fix this up.

**Comment by fbennett** [comment]
Some tweaks in ``build.sh`` and ``dir_build`` got the command working correctly. Should work as per instructions now.
